config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  post 'comments/create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root to: 'posts#top'
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_nameless_title

  has_one_attached :post_image

  validates :title, presence: true, length: {maximum: 40}
  validates :content, presence: true, length: {maximum: 300}
  validates :user_id, presence: true
  validates :post_image, presence: true

  belongs_to :user
  has_many :comments

  private
    def set_nameless_title
      self.title = "No Title" if title.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :icon_image

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :icon_image, presence: true

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :set_current_user
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comments = @current_user.comments.new(comment_params)
    if @comments.save
      redirect_to post_show(@comment.post), notice:"コメントを追記しました。"
    else
      flash.alert = "コメントできませんでした。"
      p "==================-"
      redirect_to post_path(@comments.post), status: :unprocessable_entity
    end
  end

  def destroy

  end

  private
    def comment_params
      params.require(:comment).permit(:comment_text, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :show, :edit, :destroy]
  before_action :not_login_user, only: [:new, :create, :update, :destroy, :show, :index, :edit]

  def top
  end

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "新規「#{@post.name}」を投稿しました。"
    else
      flash.alert = "投稿失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "更新しました。"
    else
      flash.alert = "更新失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.del_flag = 1
    @post.save
    redirect_to posts_path, notice: "削除しました。"
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def index
    @post = @current_user.posts
  end

  def edit
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :post_image)
    end

    def set_post
      @post = @current_user.posts.find_by(id: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "ログインしました。"
    else
      flash.notice = "ログイン失敗しました。"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice:"ログアウトしました。"
  end

  private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :not_login_user, only: [:show, :index, :edit]
  before_action :login_user, only: [:new, :creates]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_url, notice: "新規登録しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def index
    @users = User.all
  end

  def edit
  end

  private 
    def user_params
      params.require(:user).permit(:name, :email, :icon_image, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def set_current_user
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id]) 
    end
  end

  def not_login_user
    if @current_user == nil
      redirect_to login_path, notice: "ログインが必要です。"
    end
  end

  def login_user
    if @current_user
      redirect_to root_path, notice: "既にログインしています。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<div>
  <%= form_with model: @comment, url: comments_create_path do |f| %>
    <%= f.label :comment_text %>
    <%= f.text_field :comment_text, class:"form-control mt-2" %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit "コメント追加" , class:"btn btn-primary mt-2"%>
  <% end %>
</div>

app/views/layouts/_message.html.erb
<div class="container-fluid my-2">
  <%= tag.div flash.notice, class:"alert alert-warning" if flash.notice.present? %>
  <%= tag.div flash.alert, class:"alert alert-danger" if flash.alert.present? %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <%= link_to "PHOT_APP", root_path, class:"navbar-brand text-light " %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ">
        <% navClass = "nav-item nav-link active px-3 text-light" %>
        <% if @current_user %>
          <%= link_to "Users", users_path, class:navClass %>
          <%= link_to "NewPost", new_post_path, class:navClass %>
          <%= link_to "Posts", posts_path , class:navClass%>
          <%= link_to "Logout", logout_path, class:navClass %>
        <% else %>
          <%= link_to "Signin", new_user_path, class:navClass %>
          <%= link_to "Login", login_path, class:navClass %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KisakiApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <div class="container">
        <%= render 'layouts/message' %>
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model:@post do |f| %>

    <%=tag.div class:"form-group" %>
      <%= f.label :title %>    
      <%= f.text_field :title, class:"form-control" %>

    <%= tag.div class:"form-group" %>
      <%= f.label :content %>
      <%= f.text_area :content, class:"form-control"%>

    <%= tag.div class:"form-group" %>
      <%= f.label :post_image %>
      <%= tag.div f.file_field :post_image %>
    
    <%= f.submit "投稿", class:"btn btn-primary mt-4" %>
  <% end %>

app/views/posts/edit.html.erb
<%= tag.h2 "投稿編集", class:"mt-3" %>

<%= render partial:'form' %>

app/views/posts/index.html.erb
<%= tag.h2 "投稿一覧", class:"mt-4" %>
  <table class="table table-hover">
    <thead class="table-primary">
      <%= tag.tr %>
        <%= tag.th Post.human_attribute_name(:title) %>
        <%= tag.th Post.human_attribute_name(:content) %>
        <%= tag.th Post.human_attribute_name(:post_image) %>
        <%= tag.th Post.human_attribute_name(:created_at) %>
    </thead>
    <tbody>
      <% @post.each do |post| %>
        <% if post.del_flag != 1 %>
          <%= tag.tr %>
            <%= tag.td link_to post.title, post %>
            <%= tag.td post.content %>
            <%= tag.td image_tag post.post_image, style:"height: 70px;" if post.post_image.attached? %>
            <%= tag.td l post.created_at %>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/posts/new.html.erb
<%= tag.h2 "新規投稿", class:"mt-3" %>

<%= render partial:'form' %>

app/views/posts/show.html.erb
<%= tag.h2 "#{@post.user.name}の投稿" %>
  <div class="row mt-4">
    <div class="col">
      <%= image_tag @post.post_image, style:"width: 250px;" %>
    </div>
    <div class="col">
      <%= tag.h4 @post.title %>
      <%= tag.div @post.content %>
      <div class="d-flex flex-row my-3">
        <%= button_to "編集", edit_post_path(@post.id), method: :get, class:"btn btn-primary" %>
        <%= button_to "削除", @post, method: :delete, form: {data: {turbo_confirm: "「#{@post.title}」を削除します。よろしいですか？"}}, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
  <div class="comments my-4">
    <%= render "comments/new" %>
  </div>
  <div class="comments mb-4">
    <%= "コメント一覧" %>
      <% if @comment%>
        <% @comments.each do |comment| %>
          <div class="card mt-2">
            <div class="d-flex justify-content-left">
              <%= image_tag comment.user.icon_image, class:"mx-3", style: "width:80px; border-radius:40px" %>
              <div class="mt-1" >
                <%= tag.div "#{comment.user.name}のコメント"%>
                <%= tag.div comment.comment_text %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
  <div>

app/views/posts/top.html.erb
<h1>Posts#top</h1>
<p>Find me in app/views/posts/top.html.erb</p>

app/views/users/_form.html.erb
<%= form_with model:@user do |f| %>
  <div class="form-group mt-3">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </div>
  <div class="form-group mt-4">
    <%= f.label :icon_image %> :
    <%= f.file_field :icon_image, class:"px-4" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  <%= f.submit "新規登録", class:"btn btn-primary mt-3" %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<%= tag.h2 "ユーザー一覧" %>
  <div class="table-respondive">
    <table class="table table-hover text-nowrap">
      <thead class="table-primary">
        <%= tag.tr %>
          <%= tag.th User.human_attribute_name(:name) %>
          <%= tag.th User.human_attribute_name(:email) %>
          <%= tag.th User.human_attribute_name(:created_at) %>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% if user.del_flag != 1 %>
            <%= tag.tr %>
              <td class="d-flex align-items-start">
                <%= image_tag user.icon_image, style:"width: 80px; border-redius: 30%;" if user.icon_image.attached?%>
                <%= link_to user.name, user %>
              </td>
              <%= tag.td user.email %>
              <%= tag.td l user.created_at %>
          <% end %>
        <% end %>
      </tbody>
    <table>
  </div>

app/views/users/new.html.erb
<%= tag.h2 "ユーザー登録", class: "mt-3"%>
<%= render partial:"form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>